=== Nowels033/Marcas/xml/EXAMENFINAL/DAM1_LM_Final3_Noel_Dominguez.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="libreria">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="libro" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="aÃ±o">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1500"></xs:minInclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="categoria">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Ficcion"/>
                                    <xs:enumeration value="No Ficcion"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="titulo" type="xs:string"></xs:element>
                        <xs:element name="autor" type="xs:string" minOccurs="0"></xs:element>
                        <xs:element name="precio" type="tipoPrecio">
                            
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    
</xs:element>

<xs:complexType name="tipoPrecio"> 
        <xs:choice>
            <xs:element name="euros" ></xs:element>
            <xs:element name="dolares"></xs:element>         
        </xs:choice>
        <xs:attribute name="cantidad">
            <xs:simpleType>
                <xs:restriction base="xs:decimal">
                    <xs:maxInclusive value="100"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
</xs:complexType>



</xs:schema>

=== Nowels033/Marcas/xml/EXAMENFINAL/DAM1_LM_FINAL3_Noel_Dominguez.xml
<?xml version="1.0" encoding="UTF-8"?>


<!-- <!DOCTYPE libreria [ 
<!ELEMENT libreria (libro)*>
<!ELEMENT libro (año,categoria,titulo,autor?,precio)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT precio (euros|dolares)>
<!ELEMENT euros EMPTY>
<!ELEMENT dolares EMPTY>
<!ATTLIST precio cantidad CDATA #REQUIRED>
]> -->


<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DAM1_LM_Final3_Noel_Dominguez.xsd">
    <libro>
        <año>1600</año>
        <categoria>Ficcion</categoria>
        <titulo>El señor de los anillos</titulo>
        <autor>J.K</autor>
        <precio cantidad="99.9">
            <euros/>    

        </precio>

    </libro>

    <libro>
        <año>2000</año>
        <categoria>Ficcion</categoria>
        <titulo>Star wars</titulo>
        <autor>George Lucas</autor>
        <precio cantidad="100">
            <dolares/>
        </precio>
    </libro>

    <libro>
        <año>2010</año>
        <categoria>No Ficcion</categoria>
        <titulo>El arte de la guerra</titulo>
        <autor>Carl Von </autor>
        <precio cantidad="99"> 
            <euros />   
        </precio>
    </libro>

    <libro>
        <año>2010</año>
        <categoria>No Ficcion</categoria>
        <titulo>El arte de la guerra II</titulo>
        <autor>Carl Von </autor>
        <precio cantidad="100">
            <dolares/>
        </precio>
    </libro>

  

</libreria>
